---
title: " ggpubr"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggpubr)
library(ggplot2)
```


### load data 
```{r}
set.seed(123)
df <- data.frame(sex=factor(rep(c("F","M"), each=200)), weight=c(rnorm(200,55), rnorm(200, 58)))
```

### density plot
```{r}
ggdensity(df, x="weight", add="mean", rug=TRUE, color = "sex", fill="sex",palette = c("#00AFBB", "#E7B800"))
```

### histogram plot 
```{r}
gghistogram(df, x="weight", add = "mean", rug = TRUE, color = "sex", fill = "sex",
            palette = c("#00AFBB", "#E7B800"))
```
```{r}
data("ToothGrowth")
df1 <- ToothGrowth
my_comparisons <- list(c("0.5", "1"), c("1", "2"), c("0.5", "2"))
```

### boxplot
```{r}
ggboxplot(df1, x="dose", y="len", color = "dose", 
          palette = c("#00AFBB", "#E7B800", "#FC4E07"), 
          add = "jitter", shape="dose")+
          stat_compare_means(comparisons = my_comparisons)+ 
          stat_compare_means(label.y = 50)
```

### violin 
```{r}
ggviolin(df1, x="dose", y="len", fill = "dose", 
         palette = c("#00AFBB", "#E7B800", "#FC4E07"), 
         add = "boxplot", add.params = list(fill="white"))+ 
    stat_compare_means(comparisons = my_comparisons, label = "p.signif")+ #label这里表示选择显著性标记（星号） 
    stat_compare_means(label.y = 50)
```
```{r}
data("mtcars")
df2 <- mtcars
df2$cyl <- factor(df2$cyl)
df2$name <- rownames(df2) #添加一行name
```

### barplot
```{r}
ggbarplot(df2, x="name", y="mpg", fill = "cyl", color = "white", 
          palette = "npg", #杂志nature的配色 
          sort.val = "desc", #下降排序 
          sort.by.groups=FALSE, #不按组排序 
          x.text.angle=60)
# 按组进行排序
ggbarplot(df2, x="name", y="mpg", fill = "cyl", color = "white", 
          palette = "aaas", #杂志Science的配色 
          sort.val = "asc", #上升排序,区别于desc，具体看图演示 
          sort.by.groups=TRUE,x.text.angle=60) #按组排序 x.text.angle=90
```

### 偏差图: 展示与参考值之间的偏差
```{r}
df2$mpg_z <- (df2$mpg-mean(df2$mpg))/sd(df2$mpg) # 相当于Zscore标准化，减均值，除标准差
df2$mpg_grp <- factor(ifelse(df2$mpg_z<0, "low", "high"), levels = c("low", "high"))
```
```{r}
ggbarplot(df2, x="name", y="mpg_z", fill = "mpg_grp", color = "white", 
          palette = "jco", sort.val = "asc", sort.by.groups = FALSE, 
          x.text.angle=60, ylab = "MPG z-score", xlab = FALSE, legend.title="MPG Group")

ggbarplot(df2, x="name", y="mpg_z", fill = "mpg_grp", color = "white", 
          palette = "jco", sort.val = "desc", sort.by.groups = FALSE, 
          x.text.angle=90, ylab = "MPG z-score", xlab = FALSE, 
          legend.title="MPG Group", rotate=TRUE, ggtheme = theme_minimal()) # rotate设置x/y轴对换
```

### Lollipop chart 
```{r}
### dot chart1 
ggdotchart(df2, x="name", y="mpg", color = "cyl", 
           palette = c("#00AFBB", "#E7B800", "#FC4E07"), 
           sorting = "ascending", 
           add = "segments", ggtheme = theme_pubr())
### dot chart2 
ggdotchart(df2, x="name", y="mpg", color = "cyl", 
           palette = c("#00AFBB", "#E7B800", "#FC4E07"), 
           sorting = "descending", add = "segments", rotate = TRUE, 
           group = "cyl", dot.size = 6, 
           label = round(df2$mpg), font.label = list(color="white", 
           size=9, vjust=0.5), ggtheme = theme_pubr())
### dot chart3 
ggdotchart(df2, x="name", y="mpg_z", color = "cyl", 
           palette = c("#00AFBB", "#E7B800", "#FC4E07"), 
           sorting = "descending", add = "segment", 
           add.params = list(color="lightgray", size=2), 
           group = "cyl", dot.size = 6, label = round(df2$mpg_z, 1), 
           font.label = list(color="white", size=9, vjust=0.5), 
           ggtheme = theme_pubr())+ geom_line(yintercept=0, linetype=2, color="lightgray")
```

### Cleveland 
```{r}
ggdotchart(df2, x="name", y="mpg", color = "cyl", 
           palette = c("#00AFBB", "#E7B800", "#FC4E07"), 
           sorting = "descending", 
           rotate = TRUE, dot.size = 2, y.text.col=TRUE, 
           ggtheme = theme_pubr())+ theme_cleveland()
```


### boxplot basic graphic
```{r}
set.seed(2017-10-30)
d <- data.frame(riskScore = abs(rnorm(100)),
                BMI = sample(1:2, 100, replace=T),
                stage = sample(1:2, 100, replace=T),
                age = sample(1:2, 100, replace=T),
                gender = sample(1:2, 100, replace=T))

head(d)

myboxplot <- function(x, data, col = NULL, xlab, pvalue="auto") {
  boxplot(x, data, axes = FALSE, col = col)
  axis(1, at = 1:2, labels =FALSE)
  text(1:2, y=par()$usr[3]-0.08*(par()$usr[4]-par()$usr[3]),
       srt=60, xpd=T, adj=1, labels = xlab)
  if (pvalue == "auto") {
    pvalue <- round(t.test(x, data=data)$p.value, 3)
  }
  
  if (!is.null(pvalue)) {
    plab <- paste("p =", pvalue)
    text(1.5, y = par()$usr[4]*1.05, xpd=T, label=plab, col=col)
  }
}

layout(t(1:4))
par(oma=c(2, 4, 4, 0), mar=c(5,2,1,1), cex=1)

myboxplot(riskScore~age, data=d, col='red', xlab=c("age < 60", "age > 60"))
axis(2, las=1)
myboxplot(riskScore~gender, data=d, col='green', xlab=c("Male", "Female"))
myboxplot(riskScore~stage, data=d, col='blue', xlab=c("pStage 1", "pStage 2"))
myboxplot(riskScore~BMI, data=d, col='cyan', xlab=c("BMI < 24", "BMI > 24"))
```

