---
title: "Scripts"
output: 
  html_document:
    highlight: tango
    toc: true
    toc_float:
      collapsed: true
---

Examples to plot in daily life
==============================

description
--------------------

Scripts to apply for daily work.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T, warning=F, message=F)
library(ggplot2)
```


ggplot2 examples to be shown
----------------------------
```{r, fig.height=7, fig.width=10}
library(grid)
library(ggrepel)
library(DT)

dat <- read.csv("dataSet/EconomistData.csv")
mR2 <- summary(lm(HDI ~ CPI + log(CPI), data = dat))$r.squared
mR2 <- paste0(format(mR2, digits = 2), "%")
datatable(head(dat, 4), rownames = F)

ggplot(dat,
            mapping = aes(x = CPI, y = HDI)) +
    geom_point(mapping = aes(color = Region),
               shape = 1,
               size = 4,
               stroke = 1.5) +
    geom_smooth(mapping = aes(linetype = "r2"),
                method = "lm",
                formula = y ~ x + log(x), se = FALSE,
                color = "red") +
    geom_text_repel(mapping = aes(label = Country, alpha = labels),
                    data = transform(dat,
                                     labels = Country %in% c("Russia",
                                                             "Venezuela",
                                                             "Iraq",
                                                             "Mayanmar",
                                                             "Sudan",
                                                             "Afghanistan",
                                                             "Congo",
                                                             "Greece",
                                                             "Argentinia",
                                                             "Italy",
                                                             "Brazil",
                                                             "India",
                                                             "China",
                                                             "South Africa",
                                                             "Spain",
                                                             "Cape Verde",
                                                             "Bhutan",
                                                             "Rwanda",
                                                             "France",
                                                             "Botswana",
                                                             "France",
                                                             "US",
                                                             "Germany",
                                                             "Britain",
                                                             "Barbados",
                                                             "Japan",
                                                             "Norway",
                                                             "New Zealand",
                                                             "Sigapore"))) +
    scale_x_continuous(name = "Corruption Perception Index, 2011 (10=least corrupt)",
                       limits = c(1.0, 10.0),
                       breaks = 1:10) +
    scale_y_continuous(name = "Human Development Index, 2011 (1=best)",
                       limits = c(0.2, 1.0),
                       breaks = seq(0.2, 1.0, by = 0.1)) +
    scale_color_manual(name = "",
                       values = c("#24576D",
                                  "#099DD7",
                                  "#28AADC",
                                  "#248E84",
                                  "#F2583F",
                                  "#96503F"),
                       guide = guide_legend(nrow = 1)) +
    scale_alpha_discrete(range = c(0, 1),
                         guide = FALSE) +
    scale_linetype(name = "",
                   breaks = "r2",
                   labels = list(bquote(R^2==.(mR2))),
                   guide = guide_legend(override.aes = list(linetype = 1, size = 2, color = "red"))) +
    ggtitle("Corruption and human development") +
    theme_bw() +
    theme(panel.border = element_blank(),
          panel.grid = element_blank(),
          panel.grid.major.y = element_line(color = "gray"),
          axis.line.x = element_line(color = "gray"),
          axis.text = element_text(face = "italic"),
          legend.position = "top",
          legend.direction = "horizontal",
          legend.box = "horizontal",
          legend.text = element_text(size = 12),
          plot.title = element_text(size = 16, face = "bold"))
```


stack-bar plot
--------------

```{r, fig.height=6, fig.width=8}
library(ggthemes)
library(extrafont)
library(plyr)
library(scales)
library(tidyverse)

charts.data <- read.csv("dataSet/copper-data-for-tutorial.csv")
charts.data <- charts.data[rev(order(charts.data$product)), ]
charts.data$product <- factor(charts.data$product, levels = c("copper", "others"),
                              labels = c("Copper", "Pulp wood, Fruit, Salmon & Others"))
charts.data <- ddply(charts.data, .(year),
                     transform, pos = cumsum(percentage)-( 0.5* percentage))
datatable(head(charts.data, 4), rownames = F)

ggplot() +
  geom_bar(aes(y = percentage, x = year, fill = product),
           data = charts.data, stat="identity", color="black") +
  geom_text(data=charts.data, 
            aes(x = year, y = pos, label = paste0(percentage,"%")),
            colour="black", family="Tahoma", size=4) +
  theme(legend.position="bottom", 
        legend.direction="horizontal",
        legend.title = element_blank()) +
  scale_x_continuous(breaks=seq(2006,2014,1)) +
  scale_y_continuous(labels = dollar_format(suffix = "%", prefix = "")) +
  labs(x="Year", y="Percentage") +
  ggtitle("Composition of Exports to China (%)") +
  scale_fill_manual(values=c("#40b8d0", "#b2d183")) +
  theme(axis.line = element_line(size=1, colour = "black"),
        plot.title = element_text(hjust = 0.5, size = 14),
        panel.grid.major = element_line(colour = "#d3d3d3"), 
        panel.grid.minor = element_blank(),
        panel.border = element_blank(), 
        panel.background = element_blank()) +
  theme(plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
        text=element_text(family="Tahoma"),
        axis.text.x=element_text(colour="black", size = 10),
        axis.text.y=element_text(colour="black", size = 10))
```


pheatmap
--------

```{r, fig.height=6, fig.width=6}
library(pheatmap)

data <- matrix(runif(120,0,100),ncol = 12)
data[1] <- 200
colnames(data) <- c(paste0('tr_1_',seq(1,3)),paste0('tr_2_',seq(1,3)),
                    paste0('tr_3_',seq(1,3)),paste0('tr_4_',seq(1,3)))
rownames(data) <- c(paste0('gene',seq(1,10)))

annotation_col <- data.frame(treat = factor(rep(paste0('T',1:4), each = 3)),
                            class = factor(rep(paste0('class',1:2), each = 6)))
ann_color <- list(a = c(T1 = 'yellow', T2 = '#7570B3', T3 = 'firebrick', T4 = '#66A61E'),
                 b = c(class1 = 'blue', class2 = '#1B9E77'))
rownames(annotation_col) <- colnames(data)
data <- round(data,1)

pheatmap(data, border_color = NA, 
         color = colorRampPalette(c('#00FF00', 'white','#EE0000'))(100),
         scale = 'row', 
         cluster_cols = F, 
         cellwidth = 30, 
         cellheight = 30,
         legend = T, 
         legend_breaks = c(-2.5,0,2.5), 
         legend_labels = c('>= -2.5', '0', '<= 2.5'),
         cutree_rows = 2,
         treeheight_row = 10,
         annotation_col = annotation_col, 
         annotation_legend = T, 
         annotation_colors = ann_color, 
         annotation_names_col = T,
         display_numbers = data, 
         number_color = 'purple', 
         fontsize_number = 8,
         show_rownames = T, 
         fontsize_col = 15, 
         fontsize = 15, 
         main = 'heatmap')
```


boxplot basic graphic
---------------------
```{r, fig.height=5, fig.width=7}
set.seed(2017-10-30)
d <- data.frame(riskScore = abs(rnorm(100)),
                BMI = sample(1:2, 100, replace=T),
                stage = sample(1:2, 100, replace=T),
                age = sample(1:2, 100, replace=T),
                gender = sample(1:2, 100, replace=T))

datatable(head(d, 4), rownames = F)

myboxplot <- function(x, data, col = NULL, xlab, pvalue="auto") {
  boxplot(x, data, axes = FALSE, col = col)
  axis(1, at = 1:2, labels =FALSE)
  text(1:2, y=par()$usr[3]-0.08*(par()$usr[4]-par()$usr[3]),
       srt=60, xpd=T, adj=1, labels = xlab)
  if (pvalue == "auto") {
    pvalue <- round(t.test(x, data=data)$p.value, 3)
  }
  
  if (!is.null(pvalue)) {
    plab <- paste("p =", pvalue)
    text(1.5, y = par()$usr[4]*1.05, xpd=T, label=plab, col=col)
  }
}

layout(t(1:4))
par(oma=c(2, 4, 4, 0), mar=c(5,2,1,1), cex=1)

myboxplot(riskScore~age, data=d, col='red', xlab=c("age < 60", "age > 60"))
axis(2, las=1)
myboxplot(riskScore~gender, data=d, col='green', xlab=c("Male", "Female"))
myboxplot(riskScore~stage, data=d, col='blue', xlab=c("pStage 1", "pStage 2"))
myboxplot(riskScore~BMI, data=d, col='cyan', xlab=c("BMI < 24", "BMI > 24"))
```

geom_polygon circle
-------------------

```{r}
library(plotly)
library(RColorBrewer)
# doInstall <- TRUE  # Change to FALSE if you don't want packages installed.
# toInstall <- c("RColorBrewer")
# if(doInstall){install.packages(toInstall, repos = "http://cran.us.r-project.org")}
# lapply(toInstall, library, character.only = TRUE)

# Generate some data
nn <- 500
myData <- data.frame(X = rnorm(nn),
                     Y = rnorm(nn))

setK <- 6  # How many clusters?
clusterSolution <- kmeans(myData, centers = setK)

myData$whichCluster <- factor(clusterSolution$cluster)

splitData <- split(myData, myData$whichCluster)
appliedData <- lapply(splitData, function(df){
  df[chull(df), ]  # chull really is useful, even outside of contrived examples.
  })
combinedData <- do.call(rbind, appliedData)

ggplot(data = myData,aes(x = X, y = Y))+
  geom_polygon(data = combinedData,  # This is also a nice example of how to plot
              aes(x = X, y = Y, fill = whichCluster),  # two superimposed geoms
              alpha = 1/2)+                             # from different data.frames
              geom_point(size=1)+
              coord_equal()+
              scale_fill_manual(values = colorRampPalette(rev(brewer.pal(11, "Spectral")))(setK))

```

