---
title: "signaling pathway impact analysis"
date: "2020-8-10"
output: 
  html_notebook:
    codes: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(dplyr)
library(tibble)
library(data.table)
library(ToPASeq)
```


### load data 
```{r}
prof <- fread("stringtie_filtered_TPM.tsv") %>% 
    column_to_rownames("V1")
phen <- read.csv("phenotype.csv")
```


### expressionset function
```{r}
SPIA_fun <- function(x, y, 
                    group_col,
                    batch, 
                    occurrence=0.2){
  
  phe <- x %>% dplyr::filter(Group%in%group_col) %>%
    dplyr::filter(Batch%in%batch) %>%
    dplyr::mutate(Group=factor(as.character(Group)),
                  Batch=factor(as.character(Group))) 
  
  sid <- intersect(phe$SampleID_v2, colnames(y))
  phe.cln <- phe %>% dplyr::filter(SampleID_v2%in%sid) %>%
    column_to_rownames("SampleID_v2")
  prf.cln <- y %>% rownames_to_column("tmp") %>% 
    dplyr::filter(apply(dplyr::select(., -one_of("tmp")), 1, function(x) {
            sum(x != 0)/length(x)}) > occurrence) %>%
    dplyr::select(c(tmp, rownames(phe.cln))) %>%
    column_to_rownames("tmp")
  
  # determine the right order between profile and phenotype 
  for(i in 1:ncol(prf.cln)){ 
    if (!(colnames(prf.cln)[i] == rownames(phe.cln)[i])) {
      stop(paste0(i, " Wrong"))
    }
  }
  
  # change ensemble id into symbol
  require(org.Mm.eg.db)
  require(clusterProfiler)
  gene.df <- bitr(rownames(prf.cln), fromType = "ENSEMBL",
          toType = c("ENSEMBL", "SYMBOL"),
          OrgDb = org.Mm.eg.db)
  mdat <- inner_join(gene.df, 
                     prf.cln %>% rownames_to_column("ENSEMBL"),
                     by = "ENSEMBL") %>%
    dplyr::select(-ENSEMBL) 
  mdat$median <- apply(mdat[, -1], 1, median)
  mdat.cln <- with(mdat,
                       mdat[order(SYMBOL, median, decreasing = T), ])
  mdat.cln.new <- mdat.cln[!duplicated(mdat.cln$SYMBOL), ] %>%
    dplyr::select(-median)
  rownames(mdat.cln.new) <- NULL
  mdat.cln.new <- mdat.cln.new  %>% column_to_rownames("SYMBOL")
  
  pathways <- pathways("mmusculus", "kegg")
  res <- SPIA(mdat.cln.new,
              phe.cln$Group,
              pathways, 
              type = "RNASeq", 
              convertTo = "SYMBOL", 
              logFC.th = -1)
  return(res)
}
```


```{r}
SPIA_fun(phen, prof, group_col=c("ABC", "ABC_NC"), batch=c("public"))
```


### version
```{r}
sessionInfo()
```