---
title: "Differential analysis"
output:
  html_notebook:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
library(dplyr)
library(tibble)
library(data.table)
library(DESeq2)
library(ggplot2)
```

### load data 
```{r}
prof <- fread("stringtie_filtered_counts.tsv") %>%
  column_to_rownames("V1")
phen <- read.csv("phenotype.csv")
```

### function
```{r}
Deseq2fun <- function(group_col, batch,
                      occurrence=0.2, ncount=10){

  idx <- c("Group", "Batch")
  sid <- intersect(phen$SampleID_v2, colnames(prof))
  phe <- phen %>% dplyr::select(SampleID_v2, idx) %>%
    filter(SampleID_v2%in%sid) %>%
    filter(Group%in%group_col) %>%
    filter(Batch%in%batch) %>% 
    mutate(Batch=factor(Batch, levels = btc)) %>%
    arrange(factor(Group, levels = grp))
  prf <- prof %>% dplyr::select(as.character(phe$SampleID_v2)) %>% 
    rownames_to_column("Type") %>% 
    filter(apply(dplyr::select(., -one_of("Type")), 1, 
                 function(x){sum(x != 0)/length(x)}) > occurrence) %>%
            data.frame(.) %>% 
    column_to_rownames("Type")
  prf <- prf[rowSums(prf) > ncount, ]
  
  # judge no row of profile filter
	if (nrow(prf) == 0) {
		stop("No row of profile to be choosed\n")
	}
  
  # determine the right order between profile and phenotype 
  for(i in 1:ncol(prf)){ 
    if (!(colnames(prf)[i] == phe$SampleID_v2[i])) {
      stop(paste0(i, " Wrong"))
    }
  }
  
  dds <- DESeqDataSetFromMatrix(countData=prf, 
                              colData=phe,
                              design=~Group)
  
  dds <- DESeq(dds)
  res <- results(dds, pAdjustMethod = "fdr", alpha = 0.05) %>% na.omit()
  res <- res[order(res$padj), ]
  return(list(dds=dds, results=res))
}

volcanofun <- function(des_res, pval_cutoff=1.3, group_col){
  
  # Gather Log-fold change and FDR-corrected pvalues from DESeq2 results
  ## If fold-change > 0 and pvalue > pval_cutoff (Increased significant)
  ## If fold-change < 0 and pvalue > pval_cutoff (Decreased significant)
  ## - Change pvalues to -log10 (1.3 = 0.05)
  dat <- data.frame(gene = row.names(des_res),
                     pval = -log10(des_res$padj), 
                     lfc = des_res$log2FoldChange) %>%
    na.omit() %>% 
    mutate(color = case_when(lfc > 0 & pval > pval_cutoff ~ "Increased",
                             lfc < 0 & pval > pval_cutoff ~ "Decreased",
                             pval < pval_cutoff ~ "nonsignificant"))
  
  xlabel <- paste(group_col, collapse = " / ")
  
  # Make a basic ggplot2 object with x-y values
  pl <- ggplot(dat, aes(x = lfc, y = pval, color = color)) + 
    ggtitle(label = "Volcano Plot", subtitle = "Colored by fold-change direction") +
    geom_point(size = 2.5, alpha = 0.8, na.rm = T) +
    scale_color_manual(name = "Directionality",
                       values = c(Increased = "#008B00", 
                                  Decreased = "#CD4F39", 
                                  nonsignificant = "darkgray")) +
    xlab(paste0("log[2]", " (", xlabel, ")")) + 
    ylab(expression(-log[10]("adjusted p-value"))) + 
    geom_hline(yintercept=pval_cutoff, alpha=.8, linetype=2, size=1) + 
    scale_y_continuous(trans = "log1p") + 
    theme_bw(base_size = 14) + 
    theme(legend.position = "right")
  return(pl)
}

heatFun <- function(dds_res, ncount, group_col=c("TAC", "TAC_NC")){
  
  # dds_res <- TAC_vs_TACNC
  # ncount <- 40
  # group_col=c("TAC", "TAC_NC")
  
  # Convert all samples to rlog
  ddsrlog <- rlog(dds_res$dds, blind = FALSE)
  sig <- subset(dds_res$results, padj < 0.05)
  # Gather 40 significant genes and make matrix
  mat <- assay(ddsrlog[row.names(sig)])[1:ncount, ] %>%
    data.frame()
  
  # change ensemble id into symbol
  require(org.Mm.eg.db)
  require(clusterProfiler)
  gene.df <- bitr(rownames(mat), fromType = "ENSEMBL",
          toType = c("ENSEMBL", "SYMBOL"),
          OrgDb = org.Mm.eg.db)
  mdat <- inner_join(gene.df, 
                     mat %>% rownames_to_column("ENSEMBL"),
                     by = "ENSEMBL") %>%
    dplyr::select(-ENSEMBL) %>%
    column_to_rownames("SYMBOL")
  
    
  # Choose which column variables you want to annotate the columns by.
  annotation_col <- data.frame(
      Group = factor(colData(ddsrlog)$Group), 
      row.names = rownames(colData(ddsrlog))
    )
  
  # Specify colors you want to annotate the columns by.
  # if(length(pmatch(group_col, c("TAC", "TAC_NC"))[!is.na(pmatch(group_col, c("TAC", "TAC_NC")))]) == 2){
  #   ann_colors <- list(Group=c(TAC=grp.col[1], TAC_NC=grp.col[2])) 
  # }else if(length(pmatch(group_col, c("HF", "HF_NC"))[!is.na(pmatch(group_col, c("HF", "HF_NC")))]) == 2){
  #   ann_colors <- list(Group=c(HF=grp.col[3], HF_NC=grp.col[4])) 
  # }else{
  #   ann_colors <- list(Group=c(TAC=grp.col[1], HF=grp.col[3]))
  # }
  
    match_color <- function(grp_lab){
  
      grp_idx <- pmatch(grp_lab, grp)
      grp_lab_col <- grp.col[grp_idx]
      
      return(list(Group=grp_lab_col))
    } 
  ann_colors <- match_color(unique(as.character(colData(ddsrlog)$Group)))
 
  names(ann_colors$Group) <- unique(as.character(colData(ddsrlog)$Group))
  
  require(pheatmap)
  require(RColorBrewer)
  # Make Heatmap with pheatmap function.
  pheatmap(mat = mdat, 
           color = colorRampPalette(c("#19499B", "white", "#E5211A"))(100), 
           scale = "row", # Scale genes to Z-score (how many standard deviations)
           annotation_col = annotation_col, # Add multiple annotations to the samples
           annotation_colors = ann_colors,# Change the default colors of the annotations
           fontsize = 8, # Make fonts smaller
           cellwidth = 10, # Make the cells wider
           cluster_cols = FALSE,
           show_rownames = T,
           treeheight_row = 0,
           show_colnames = T)
}

get_gesa <- function(dds_res){
  #dds_res <- TAC_vs_TACNC
  
  sig_gene <- subset(dds_res$results, padj < 0.05)
  # change ensemble id into symbol
  require(org.Mm.eg.db)
  require(clusterProfiler)  
  gene_all <- bitr(rownames(sig_gene), fromType = "ENSEMBL",
          toType = c("ENSEMBL", "SYMBOL", "ENTREZID"),
          OrgDb = org.Mm.eg.db)

  # KEGG over-representation test
  kegg <- enrichKEGG(
              gene = gene_all$ENTREZID, 
              organism = 'mmu', 
              keyType = 'kegg', 
              pvalueCutoff = 0.05,
              pAdjustMethod = 'BH', 
              minGSSize = 3,
              maxGSSize = 500,
              qvalueCutoff = 0.2,
              use_internal_data = FALSE)
  
  # GO over-representation test
  go <- enrichGO(
                gene = gene_all$ENTREZID, 
                keyType = 'ENTREZID',
                OrgDb="org.Mm.eg.db",
                ont = "bp", 
                pvalueCutoff = 0.05,
                pAdjustMethod = 'BH',
                qvalueCutoff = 1, 
                readable = TRUE)
  
  return(list(kegg=kegg, go=go))
}

```


